### ISSUE TITLE
Not working on proxy

### ISSUE THREAD

**Issue by liword** [pmarks-net/ipvfoo#55] opened 2023-11-16 17:06 UTC
This is not working in Firefox when proxy is on.
Always IPv4, and ip 0.0.0.0.

**Comment by pmarks-net** [comment] 2023-11-16 19:08
Duplicate of #5 

When using a proxy, the browser doesn't know the server IP address.  IPvFoo could fake the answer by doing its own DNS lookups, but that would violate the "Everything is captured privately without creating any additional network traffic" constraint.

**Closed by pmarks-net** 2023-11-16 19:08 UTC
